// Generated by https://quicktype.io

export type GuideReturns = GuideItemReturns[]

export interface GuideItemReturns {
  title: string
  privileges: Privilege[]
}

export interface ResultStatusReturns {
  authenticated: number
  account: string
  enterprise_name: string
  order_redirect: string
  privileges: Privilege[]
}

export interface Privilege {
  title: string
  sub_title?: string
  icon: string
}

export interface VerifyEmailReturns {
  partner_enterprise: number
  form_field: FormField
}

export interface FormField {
  employee_no: number
  idcard: number
  employee_card: number
}
