export interface CantonSelects {
  code: number
  status: number
  data: CantonSelect
}
export interface CantonSelect {
  store_list: StoreList[]
  total_count: number
}

interface StoreList {
  id: number
  city_id: number
  store_name: string
  store_code: string
  store_address: string
  store_contact: string
  system_code: string
  type: number
  operating_state: number
  is_active: number
  dt_created: string
  dt_updated: string
}

export interface CantonCitys {
  code: number
  status: number
  data: CantonCity
}

export interface CantonCity {
  data: Datum[]
}

interface Datum {
  id: number
  city_id: number
  city_name: string
  parent_id: number
  operator_channel: number
  firstLetter: string
  is_active: number
  dt_created: string
  dt_updated: string
}

export interface CantonDetails {
  code: number
  status: number
  data: CantonDetail
}

export interface CantonDetail {
  data: Data
}

interface Data {
  id: number
  city_id: number
  store_name: string
  store_code: string
  store_address: string
  store_contact: string
  system_code: string
  type: number
  operating_state: number
  is_active: number
  dt_created: string
  dt_updated: string
  city_name: string
}

// Generated by https://quicktype.io
