// Generated by https://quicktype.io

export interface HomeNgcacheReturns {
  festival: Festival
  brand: Brand
  banner: Banner
  brand_endorsement: BrandEndorsement
  icons: Icons
  three_palace: Banner
  recommend: Recommend
  subject: Subject
  brand_story: BrandStoryClass
}

export interface UserInfo {}

export interface HomeDataReturns extends HomeNgcacheReturns {
  popup: Popup
  userInfo?: UserInfo
}

export interface Festival {
  is_festival: number
  image: string
}

export interface Banner {
  model_title: string
  model_data: BannerModelDatum[]
}

export interface BannerModelDatum {
  image: string
  type: string
  product_id: string
  tag_id: string
  skip_url: string
}

export interface Brand {
  model_title: string
  model_data: BrandModelDatum[]
}

export interface BrandModelDatum {
  name: string
  positioning: string
}

export interface BrandEndorsement {
  model_title: string
  model_data: BrandEndorsementModelDatum[]
}

export interface BrandEndorsementModelDatum {
  icon: string
  text: string
}

export interface Icons {
  model_title: string
  model_data: IconsModelDatum[]
}

export interface IconsModelDatum {
  brand_id: number
  is_more_icon: number
  main_icon: string
  sub_icon: string
}

export interface Recommend {
  model_title: string
  model_data: ProductElement[]
}

export interface ProductElement {
  product_id: number
  image: string
  name: string
  tag: string
  price: string
  price_unit: string
  base_fee: string
  assurance?: string
  assurance_divide?: string
  property_tags?: string[]
}

export interface Subject {
  model_title: string
  model_data: SubjectModelDatum[]
}

export interface SubjectModelDatum {
  header_img: string
  products: ProductElement[]
}

export interface Popup {
  id: string
  img: string
  redirect_url: string
  is_active: string
  create_time: string
}

// Generated by https://quicktype.io

export interface BrandStory {
  brand_story: BrandStoryClass
}

export interface BrandStoryClass {
  model_title: string
  model_data: ModelDatum[]
}

export interface ModelDatum {
  icon: string
  title: string
  desc: string
}

export interface UserTagReturns {
  model_title: string
  model_data: ModelData[]
}

export interface ModelData {
  image: string
  type: string
  user_tag: string
  product_id: number
  tag_id: number
  skip_url: string
  ext: EXT
}

export interface EXT {
  expire_datetime: number
  expire_title: string
}
