// Generated by https://quicktype.io

export type NavIconsReturns = {
  is_festival: number
  icons: NavIcons[]
}

export interface NavIcons {
  icon: string
  select_icon: string
  text: string
}

export type CheckTradeDoneReturns = {
  is_have_undone_trade: boolean
  tips: string
}
