// Generated by https://quicktype.io

export interface CancelReturns {
  confirm_layer: ConfirmLayer
  botton_text: string
  reason_info: ReasonInfo[]
  cancel_type: string
  contract_type: string
  release_price: string
  old_sku_info: SkuInfo
  sku_info: SkuInfo
  page_title: string
  release_text: string
}

export interface ConfirmLayer {
  title: string
  text: string
  left_btn_txt: string
  right_btn_txt: string
}

export interface SkuInfo {
  image: string
  name: string
}

export interface ReasonInfo {
  reason_id: number
  reason_text: string
}

// Generated by https://quicktype.io

export interface CancelResultReturns {
  cancel_result: number
  page_title: string
  result_title: string
  result_text: string
  sku_info: SkuInfo
  old_sku_info: SkuInfo
  cancel_reason: string
  reason_dec: string
  cancel_type: string
  contract_type: string
  release_price: string
  cancel_date: string
}
