// Generated by https://quicktype.io

export interface ServiceListReturns {
  list: ServiceListItem[]
  has_more: boolean
}

export interface ServiceListItem {
  contract_no: string
  is_ali_small: boolean
  returnflow_trade_no?: string
  returnflow_type?: string
  returnflow_sub_trade_no?: string
  trade_no: string
  show_text: string
  color_type: number
  contract_status: number
  repayment_amount: string
  next_pay_date: string
  logistics_tip?: string
  sku_info: SkuInfo
  button_group: ButtonGroup[]
  label_group: LabelGroup[]
  pis_code?: string
  pay_no?: string
}

export interface ButtonGroup {
  button_name: string
  button_type: string
  button_link: string
  button_tip?: string
  sort: number
  child_button_list?: ChildButtonList[]
}

export interface ChildButtonList {
  button_type: string
  button_name: string
  button_link: string
}

export interface LabelGroup {
  label_name: string
  label_link: string
  label_type: string
}

export interface SkuInfo {
  sku_name: string
  sku_img_url: string
}

export interface CheckReturnStatus {
  return_status: number
  title: string
  msg: string
}

export interface CheckReplaceMent {
  is_replace_role: boolean
}

export interface CheckBuyOutStatus {
  return_status: number
  title: string
  msg: string
}
