// App
export const INIT_TABBAR = 'INIT_TABBAR'
export const TOGGLE_TABBAR = 'TOGGLE_TABBAR'
export const HIDDEN_TABBAR = 'HIDDEN_TABBAR'
export const RAS_PRIVATE_KEY = 'RAS_PRIVATE_KEY'
export const GET_NAV_ICONS = 'GET_NAV_ICONS'
export const CHECK_TRADE_DONE = 'CHECK_TRADE_DONE'

// cache-list
export const GET_CACHE_LIST = 'GET_CACHE_LIST'
export const REMOVE_CACHE = 'REMOVE_CACHE'
export const REMOVE_ALL_CACHE = 'REMOVE_ALL_CACHE'

// index
export const GET_HOME_INFO = 'GET_HOME_INFO'
export const GET_HOME_USER_TAG = 'GET_HOME_USER_TAG'

// product/category
export const GET_PRODUCT_CATEGORY_INFO = 'GET_PRODUCT_CATEGORY_INFO'
export const CHANGE_PRODUCT_CATEGROY_BRAND_ID = 'CHANGE_PRODUCT_CATEGROY_BRAND_ID'

// product/brands
export const GET_PRODUCT_BRANDS_INFO = 'GET_PRODUCT_BRANDS_INFO'

// product/detail
export const GET_PRODUCT_DETAIL_INFO = 'GET_PRODUCT_DETAIL_INFO'
export const GET_PRODUCT_PROPERTY = 'GET_PRODUCT_PROPERTY'
export const CHANGE_PROPERTY_ITEM = 'CHANGE_PROPERTY_ITEM'
export const CHANGE_PROPERTY_ITEM_DEFAULT_SELECTED = 'CHANGE_PROPERTY_ITEM_DEFAULT_SELECTED'
export const CHANGE_POPUP_MODAL_ID = 'CHANGE_POPUP_MODAL_ID'
export const CHANGE_VAS_LIST_SELECTED = 'CHANGE_VAS_LIST_SELECTED'

// product/introduce
export const GET_PRODUCT_INTRODUCE_INFO = 'GET_PRODUCT_INTRODUCE_INFO'

// product/comment
export const OPEN_PRODUCT_COMMENT_MODAL = 'OPEN_PRODUCT_COMMENT_MODAL'
export const CLOSE_PRODUCT_COMMENT_MODAL = 'CLOSE_PRODUCT_COMMENT_MODAL'
export const FETCH_PRODUCT_COMMENTS = 'FETCH_PRODUCT_COMMENTS'
export const LOAD_MORE_PRODUCT_COMMENTS = 'LOAD_MORE_PRODUCT_COMMENTS'

// product/video-detail
export const GET_VIDEO_DETAIL_INFO = 'GET_VIDEO_DETAIL_INFO'

// easeu
export const CHECK_FLOW = 'CHECK_FLOW'
export const GET_TRADE_INDEX = 'GET_TRADE_INDEX'
export const GET_TRADE_SUCCESS = 'GET_TRADE_SUCCESS'

export const SEND_SMS_CODE = 'SEND_SMS_CODE'

// returnflow
export const GET_DETAIL_INFO = 'GET_DETAIL_INFO'
export const GET_ORDER_DETAIL_INFO = 'GET_ORDER_DETAIL_INFO'
export const GET_RESULTS_INFO = 'GET_RESULTS_INFO'

// site/appdownload
export const FETCH_APPDOWNLOAD_LIST = 'FETCH_APPDOWNLOAD_LIST'
export const FETCH_APPDOWNLOAD_PROCEED = 'FETCH_APPDOWNLOAD_PROCEED'

// trade/form/info
export const FETCH_CHINA_UNICOM_USER_DATA = 'FETCH_CHINA_UNICOM_USER_DATA'
export const SAVE_TRADE_INFO_WHEN_UNMOUNT = 'SAVE_TRADE_INFO_WHEN_UNMOUNT'
export const CLEAR_TRADE_INFO_AFTER_SUBMITTED = 'CLEAR_TRADE_INFO_AFTER_SUBMITTED'

// account/center
export const GET_USER_INFO = 'GET_USER_INFO'
export const FETCH_CENTER_INFO = 'FETCH_CENTER_INFO'

// account/privilege
export const FETCH_PRIVILEGE_LIST = 'FETCH_PRIVILEGE_LIST'
export const FETCH_USER_PRIVILEGE_LIST = 'FETCH_USER_PRIVILEGE_LIST'
export const EXCHANGE_PRIVILEGE = 'EXCHANGE_PRIVILEGE'

// account/footprint
export const GET_ACCOUNT_FOOTPRINT_INFO = 'GET_ACCOUNT_FOOTPRINT_INFO'
export const GET_ACCOUNT_FOOTPRINTLIST_INFO = 'GET_ACCOUNT_FOOTPRINTLIST_INFO'

// account/unionPay
export const FETCH_UNION_PAY_LIST = 'FETCH_UNION_PAY_LIST'
export const FETCH_UNION_PAY_DETAIL = 'FETCH_UNION_PAY_DETAIL'
export const FETCH_UNION_PAY_INFO = 'FETCH_UNION_PAY_INFO'
export const FETCH_UNION_PAY_CHECK_BANK_LIST = 'FETCH_UNION_PAY_CHECK_BANK_LIST'
export const GO_TO_NEXT = 'GO_TO_NEXT'
export const SAVE_FORM_FILEDS = 'SAVE_FORM_FILEDS'
export const SAVE_SMS_FILEDS = 'SAVE_SMS_FILEDS'

// account/auto-rent
export const FETCH_INFO = 'FETCH_INFO'
export const OPEN_AUTO_RENT = 'OPEN_AUTO_RENT'
export const SET_RENT_BUTTON_DISABLED = 'SET_RENT_BUTTON_DISABLED'

// repair
export const REPAIR_QUALITY_RECORD_LIST = 'REPAIR_QUALITY_RECORD_LIST'
export const LOAD_REPAIR_QUALITY_RECORD_LIST = 'LOAD_REPAIR_QUALITY_RECORD_LIST'
export const REPAIR_QUALITY_DETAIL = 'REPAIR_QUALITY_DETAIL'

export const REPAIR_STANDBY_RECORD_LIST = 'REPAIR_STANDBY_RECORD_LIST'
export const LOAD_REPAIR_STANDBY_RECORD_LIST = 'LOAD_REPAIR_STANDBY_RECORD_LIST'
export const REPAIR_STANDBY_DETAIL = 'REPAIR_STANDBY_DETAIL'

// login
export const LOGIN_TOGGLE_CACHED = 'LOGIN_TOGGLE_CACHED'

// guangzhou cmcc
export const FETCH_CANTON_STORE_CITY = 'FETCH_CANTON_STORE_CITY'
export const FETCH_CANTON_STORE_SELECT = 'FETCH_CANTON_STORE_SELECT'
export const LOAD_FETCH_CANTON_STORE_SELECT = 'LOAD_FETCH_CANTON_STORE_SELECT'
export const FETCH_CANTON_STORE_DETAIL = 'FETCH_CANTON_STORE_DETAIL'
export const SELECT_CANTON_STORE_ITEM = 'SELECT_CANTON_STORE_ITEM'

// account/buy-out
export const FETCH_BUY_OUT_INFO = 'FETCH_BUY_OUT_INFO'

// account/result
export const FETCH_BUY_OUT_RESULT_INFO = 'FETCH_BUY_OUT_RESULT_INFO'

// myaccount/bind/management
export const FETCH_BIND_WECHAT_INFO = 'FETCH_BIND_WECHAT_INFO'
export const FETCH_BIND_RESULT_INFO = 'FETCH_BIND_RESULT_INFO'

// mytrade/Certification
export const GET_CERTIFY_RESULT = 'GET_CERTIFY_RESULT'

// trade/order/confirm
export const FETCH_TRADE_ORDER_CONFIRM_INFO = 'FETCH_TRADE_ORDER_CONFIRM_INFO'
export const FETCH_ORDER_REPLACE_STATUS = 'FETCH_ORDER_REPLACE_STATUS'
export const FETCH_ORDER_REPLACE_REMOTE = 'FETCH_ORDER_REPLACE_REMOTE'
export const FETCH_ORDER_REPLACE_CHECK_CONDITION = 'FETCH_ORDER_REPLACE_CHECK_CONDITION'

// trade/order/pay
export const FETCH_TRADE_ORDER_PAY_INFO = 'FETCH_TRADE_ORDER_PAY_INFO'

// trade/order/result
export const FETCH_TRADE_ORDER_RESULT_INFO = 'FETCH_TRADE_ORDER_RESULT_INFO'

// trade/assess/result
export const FETCH_TRADE_ASSESS_RESULT_INFO = 'FETCH_TRADE_ASSESS_RESULT_INFO'

// trade/assess/list
export const FETCH_TRADE_ASSESS_LIST_INFO = 'FETCH_TRADE_ASSESS_LIST_INFO'

// terms/agreement
export const FETCH_TERMS_AGREEMENT = 'FETCH_TERMS_AGREEMENT'

// myTrade address
export const FETCH_CITY_LIST = 'FETCH_CITY_LIST'
export const FETCH_ADDRESS_FORM = 'FETCH_ADDRESS_FORM'
export const SAVE_ADDRESS_FORM = 'SAVE_ADDRESS_FORM'
export const FETCH_SELECT_LIST = 'FETCH_SELECT_LIST'
export const FETCH_SEARCH_LIST = 'FETCH_SEARCH_LIST'

// account/trade/assess
export const CHANGE_IDENTITY_STATUS = 'CHANGE_IDENTITY_STATUS'
export const RECEIVE_INFORMATION_DATA = 'RECEIVE_INFORMATION_DATA'
// mytrade/hunanMobile
export const SELECT_NEW_PHONE_NUMBER = 'SELECT_NEW_PHONE_NUMBER'

// myAccount/returnPhone/price
export const FETCH_RETURN_PHONE_PRICE = 'FETCH_RETURN_PHONE_PRICE'
export const FETCH_RETURN_PHONE_CITY = 'FETCH_RETURN_PHONE_CITY'
export const FETCH_RETURN_PHONE_CITY_REGION = 'FETCH_RETURN_PHONE_CITY_REGION'
export const FETCH_RETURN_PHONE_STORE = 'FETCH_RETURN_PHONE_STORE'
export const SELECT_RETURN_PHONE_STORE = 'SELECT_RETURN_PHONE_STORE'
export const CLEAR_RETURN_PHONE_CHOSEN_STORE = 'CLEAR_RETURN_PHONE_CHOSEN_STORE'
export const CLEAR_RETURN_PHONE_STORE_LIST = 'CLEAR_RETURN_PHONE_STORE_LIST'
export const FETCH_RETURN_PHONE_STORE_BY_ID = 'FETCH_RETURN_PHONE_STORE_BY_ID'
export const FETCH_RETURN_PHONE_DETAIL = 'FETCH_RETURN_PHONE_DETAIL'

// mytrade/funds-union
export const FETCH_AUTHORIZE_RESULT = 'FETCH_AUTHORIZE_RESULT'
export const FETCH_OPT_BILL_NO = 'FETCH_OPT_BILL_NO'

// mytrade exchange
export const FETCH_EXCHANGE_INDEX_INFO = 'FETCH_EXCHANGE_INDEX_INFO'
export const FETCH_EXCHANGE_RETURN_INFO = 'FETCH_EXCHANGE_RETURN_INFO'
export const SAVE_EXCHANGE_RETURN_INFO = 'SAVE_EXCHANGE_RETURN_INFO'
export const FETCH_EXCHANGE_STORE_INFO = 'FETCH_EXCHANGE_STORE_INFO'
export const SAVE_EXCHANGE_TAB_SHOW = 'SAVE_EXCHANGE_TAB_SHOW'

// myaccount/service/list
export const FETCH_SERVICE_LIST = 'FETCH_SERVICE_LIST'
export const FETCH_SERVICE_LIST_MORE = 'FETCH_SERVICE_LIST_MORE'

// myaccount/service/cancel
export const FETCH_SERVICE_CANCEL_INFO = 'FETCH_SERVICE_CANCEL_INFO'
export const FETCH_SERVICE_CANCEL_RESULT = 'FETCH_SERVICE_CANCEL_RESULT'
export const FETCH_SERVICE_DETAIL = 'FETCH_SERVICE_DETAIL'
export const FETCH_SERVICE_RETURN_PLAN = 'FETCH_SERVICE_RETURN_PLAN'
export const FETCH_SERVICE_TERMS_LIST = 'FETCH_SERVICE_TERMS_LIST'

// myaccount/service/privilege
export const FETCH_SERVICE_PRIVILEGE = 'FETCH_SERVICE_PRIVILEGE'

// myaccount/receipt
export const FETCH_RECEIPT_INVOICE = 'FETCH_RECEIPT_INVOICE'
export const FETCH_RECEIPT_INVOICE_CANCEL = 'FETCH_RECEIPT_INVOICE_CANCEL'
export const SAVE_RECEIPT_INVOICE_APPLY = 'SAVE_RECEIPT_INVOICE_APPLY'
export const SAVE_RECEIPT_INVOICE_EMAIL = 'SAVE_RECEIPT_INVOICE_EMAIL'

export const FETCH_RECEIPT_INVOICE_DETAIL = 'FETCH_RECEIPT_INVOICE_DETAIL'
export const LOAD_FETCH_RECEIPT_INVOICE_DETAIL = 'LOAD_FETCH_RECEIPT_INVOICE_DETAIL'

// myaccount/service/order-record
export const FETCH_SERVICE_RECORD_LIST = 'FETCH_SERVICE_RECORD_LIST'
export const FETCH_SERVICE_RECORD_DETAIL = 'FETCH_SERVICE_RECORD_DETAIL'

// myaccount/withholding/list
export const FETCH_WITHHOLDING_LIST_INFO = 'FETCH_WITHHOLDING_LIST_INFO'

// mytrade/withholding/select-type
export const FETCH_WITHHOLDING_SELECTABLE_LIST = 'FETCH_WITHHOLDING_SELECTABLE_LIST'

// mytrade/creditcard
export const FETCH_CREDIT_PAY_INFO = 'FETCH_CREDIT_PAY_INFO'
export const FETCH_CREDIT_SMS = 'FETCH_CREDIT_SMS'
export const FETCH_CREDIT_CREATE_CUP = 'FETCH_CREDIT_CREATE_CUP'
export const FETCH_CREDIT_CREATE_QUERY = 'FETCH_CREDIT_CREATE_QUERY'
export const FETCH_CREDIT_LBF_AGREEMENT = 'FETCH_CREDIT_LBF_AGREEMENT'
export const FETCH_CREDIT_COOKIE = 'FETCH_CREDIT_COOKIE'

// mytrade/extraInfo/list
export const FETCH_EXTRAINFO_LIST = 'FETCH_EXTRAINFO_LIST'

// enterprise/mytrade/pick-number
export const FETCH_ENTERPRISE_PICK_NUMBER = 'FETCH_ENTERPRISE_PICK_NUMBER'

// activitys/exchangecoupon
export const FETCH_ACTIVITYS_EXCHANGECOUPON = 'FETCH_ACTIVITYS_EXCHANGECOUPON'

// activitys/guide-old-user
export const FETCH_ACTIVITYS_GUIDE_OLD_USER = 'FETCH_ACTIVITYS_GUIDE_OLD_USER'

export const FETCH_ACTIVITYS_COUPONINFO = 'FETCH_ACTIVITYS_COUPONINFO'

// enterprise/apply
export const FETCH_ENTERPRISE_APPLY_GUIDE = 'FETCH_ENTERPRISE_APPLY_GUIDE'
export const FETCH_ENTERPRISE_APPLY_RESULT = 'FETCH_ENTERPRISE_APPLY_RESULT'
export const CHECK_ENTERPRISE_APPLY_EMAIL = 'CHECK_ENTERPRISE_APPLY_EMAIL'

// myaccount/return/apply
export const CHANGE_EXPRESS_TIME = 'CHANGE_EXPRESS_TIME'
export const CHANGE_EXPRESS_TYPE = 'CHANGE_EXPRESS_TYPE'
export const FETCH_RETURN_APPLY_DETAIL = 'FETCH_RETURN_APPLY_DETAIL'
export const GET_EXPRESS_NUMBER = 'GET_EXPRESS_NUMBER'
export const CHANGE_EXPRESS_ADDRESS = 'CHANGE_EXPRESS_ADDRESS'
export const FETCH_EXPRESS_LOGISTICS = 'FETCH_EXPRESS_LOGISTICS'
