export const AssetImage = {
  Common: {
    Loading: require('images/common/loading.gif'),
    ErrorBG: require('images/common/error-bg.png'),
    Download: require('images/common/logo-download.png'),
  },
  Home: {
    SGS: require('images/home/sign.png'),
  },
  Help: {
    Order1: require('images/help/order-1.png'),
    Order2: require('images/help/order-2.png'),
    Order3: require('images/help/order-3.png'),
    Order4: require('images/help/xd1.png'),
    Order5: require('images/help/xd2.png'),
    Order6: require('images/help/xd3.png'),
    Maintain1: require('images/help/maintain-1.png'),
    Maintain2: require('images/help/maintain-2.png'),
  },
  Activity: {
    Guidance: {
      Image1: require('images/activity/guidance/top.png'),
      Image2: require('images/activity/guidance/header.png'),
      Image3: require('images/activity/guidance/security1.png'),
      Image4: require('images/activity/guidance/security2.png'),
      Present1: require('images/activity/guidance/mian.png'),
      Present2: require('images/activity/guidance/hui.png'),
      Present3: require('images/activity/guidance/bao.png'),
      Present4: require('images/activity/guidance/huan.png'),
      Present5: require('images/activity/guidance/huabei.png'),
      Present6: require('images/activity/guidance/zhima.png'),
      Present2_1: require('images/activity/guidance/shuju.png?v=1'),
      Present3_1: require('images/activity/guidance/tiao.png'),
      Present3_2: require('images/activity/guidance/xin.png'),
      Present3_3: require('images/activity/guidance/kuai.png'),
      Present3_4: require('images/activity/guidance/zhuji.png'),
      Present4_1: require('images/activity/guidance/gui.png'),
      Present4_2: require('images/activity/guidance/xu.png'),
      Present4_3: require('images/activity/guidance/mai.png'),
      Present5_1: require('images/activity/guidance/valueAdd1.png'),
      Present5_2: require('images/activity/guidance/valueAdd2.png'),
      Present5_3: require('images/activity/guidance/valueAdd3.png'),
      Footer: require('images/activity/guidance/button.png'),
      Footerxz: require('images/activity/guidance/footerxz.png'),
    },
  },
  Account: {
    UserPrivilegeTop: require('images/account/user-privilege-top.png'),
  },
  ReturnFlow: {
    Detail: {
      returnSuccess: require('images/returnflow/detail/success.png'),
      returnWaiting: require('images/returnflow/detail/waiting.png'),
    },
  },
  Site: {
    AppDownload: {
      General: require('images/site/appdownload/banner_zx.png'),
      Weibo: require('images/site/appdownload/xiaowu.png'),
      Iphonex: require('images/site/appdownload/banner_ix.png'),
      NoviceGift: require('images/site/appdownload/banner_channel.png'),
      Weixin: require('images/site/appdownload/weixin_down.png'),
      Samsung: require('images/site/appdownload/banner_samsung.png'),
      Footer: require('images/site/appdownload/cooperation.png'),
      AHSApp: require('images/site/appdownload/aihuishou.png'),
    },
    AppDownloadProceed: {
      AppIcon: require('images/site/appdownloadproceed/appicon.png'),
    },
  },
  Trade: {
    Results: {
      AssResult: require('images/trade/results/pinggu.png'),
      AssError: require('images/trade/results/pinggu2.png'),
      PaySuccess: require('images/trade/results/banli1.png'),
      PayWait: require('images/trade/results/banli2.png'),
      ZhimaLogo: require('images/trade/results/logo_xhj_zhima.png'),
    },
  },
  MyAccount: {
    Return: {
      standard1: require('images/myaccount/return/standard1.png'),
      standard2: require('images/myaccount/return/standard2.png'),
      standard3: require('images/myaccount/return/standard3.png'),
      standard4: require('images/myaccount/return/standard4.png'),
      standard5: require('images/myaccount/return/standard5.png'),
      standard6: require('images/myaccount/return/standard6.png'),
      standard7: require('images/myaccount/return/standard7.png'),
      standard8: require('images/myaccount/return/standard8.png'),
      standard9: require('images/myaccount/return/standard9.png'),
    },
    Receipt: {
      Apply: require('images/myaccount/receipt/apply.png'),
      Success: require('images/myaccount/receipt/success.png'),
      Ziyuan: require('images/myaccount/receipt/ziyuan.png'),
      CancelZiyuan: require('images/myaccount/receipt/cancel_fapiao.png'),
    },
  },
  MyTrade: {
    Exchange: {
      One: require('images/mytrade/exchange/one.png'),
      Two: require('images/mytrade/exchange/two.png'),
      Three: require('images/mytrade/exchange/three.png'),
      Four: require('images/mytrade/exchange/four.png'),
      Five: require('images/mytrade/exchange/five.png'),
      Fangbian: require('images/mytrade/exchange/fangbian.png'),
      Chaozhi: require('images/mytrade/exchange/chaozhi.png'),
      Shengqian: require('images/mytrade/exchange/shengqian.png'),
      Mag: require('images/mytrade/exchange/msg.png'),
    },
    Creditcard: {
      Anquanma: require('images/mytrade/creditcard/anquanma.png'),
      Baizhang: require('images/mytrade/creditcard/baizhang.png'),
    },
  },
}
