// Generated by https://quicktype.io

export interface WithHoldingInfoReturns {
  page_title: string
  current_title: string
  current_doc: string
  list_title: string
  list_doc: string
  list: List[]
}

export interface List {
  code: string
  type: number
  title: string
  agreement_no: string
  icon: string
}
