// Generated by https://quicktype.io

export interface PickNumber {
  is_empty: string
  page_index: string
  page_size: string
  phone: string[]
  vas_detail: VasDetail
  title: string
  subtitle: string
  tips: string
}

export interface VasDetail {
  id: number
  type: number
  related_id: number
  name: string
  remark: string
  price: number
  image: string
  url: string
  banner_img: string
  icon: string
  order: number
  is_required: number
  is_active: number
  dt_created: string
  dt_updated: string
  flow_code: string
  has_flow: number
  tableSuffix: string
}

// Generated by https://quicktype.io

export interface SearchPhone {
  phone: string[]
}
