import cloneDeep from 'lodash.clonedeep'
import { RouterRequest } from '../../interfaces/router'
import account from '../../models/account'
import { BFA_Returns } from '../../utils/tools'

interface ConfigurationReturns {
  redirect_url: string
  content: string
}

interface GetPhoneReturns {
  id: string
  phone: string
  alipay_user_id: string
  nickname: string
  source_type: string
  is_active: string
  dt_created: string
  dt_updated: string
  tableSuffix: number
  user_id: string
}

// Generated by https://quicktype.io

export default class BindWechat {
  static async getConfiguration(req: RouterRequest): Promise<ConfigurationReturns> {
    const res = await account.getBindWechatConfiguration<ConfigurationReturns>(req)
    return BFA_Returns(res)
  }

  // 获取绑定结果信息并且调用用户信息接口拿到手机号
  static async getBindResult(req: RouterRequest) {
    const req2 = cloneDeep(req)
    req2.query.action = 'getUserInfo'
    const [res1, res2] = await Promise.all([
      account.getBindWechatConfiguration<ConfigurationReturns>(req),
      account.getUserData<GetPhoneReturns>(req2),
    ])
    if (res1.code === 200 && res2.code === 200) {
      return { ...res1.data, phone: res2.data.phone }
    } else {
      throw new Error(res1.msg || res2.msg)
    }
  }

  static async unbindWechat(req: RouterRequest): Promise<void> {
    const res = await account.unbindWechat(req)
    return BFA_Returns(res)
  }
}
