// Generated by https://quicktype.io

export interface ExchangeCouponReturns {
  brand_name: string
  recommand_product: RecommandProduct[]
  recommand_product_hot: RecommandProduct[]
  discount_amount: string
  coupon_rule_id: number
  coupon_type: number
}

export interface RecommandProduct {
  img_url: string
  product_name: string
  compare_price_desc_left: string
  compare_price_amount: string
  compare_price_desc_right: string
  activity_id: number
  reduce_price_per_day?: string
}
